name: Publish Package to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Build Kient
        run: bun run build
      
      - name: Publish
        run: pnpm publish --access public
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}